SpiffoList/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import WelcomePage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('users.urls')),
    path('listings/', include('listings.urls')),
    path('', WelcomePage.as_view(), name='welcome'),
    path("__reload__/", include("django_browser_reload.urls")),
]

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'
urlpatterns = [
	path('new', views.ListingCreationView.as_view(), name='create'),
	path('', views.ListingUserViewAll.as_view(), name='index'),
	path('<int:pk>/destroy', views.DestroyListing.as_view(), name='destroy')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
	path('profile/', views.ProfileView.as_view(), name='profile'),
	path('register/', views.RegisterProfileView.as_view(), name='register')
]

listings/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import AppUser


class Listing(models.Model):
	title = models.CharField(max_length = 50)
	listing_main_photo = models.FileField(null = True, blank = True, upload_to = "uploads/listings/")
	description = models.TextField()
	location = models.CharField(max_length = 150)
	owner = models.ForeignKey(
		AppUser, on_delete = models.CASCADE,
	)

	def __str__(self):
		returnvalue = f"{self.owner}-{self.title}"
		return returnvalue

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# since we want to only add to the User class we use AbstractUser
class AppUser (AbstractUser):

	# This will add these feilds to the database under the User I called in AppUser
	profile_picture = models.FileField(upload_to = "uploads/users/")
	address = models.TextField()
	phone_number = models.TextField()

listings/forms.py
from django import forms
from django.forms import ModelForm
from listings.models import Listing


class ListingCreationForm(ModelForm):

	class Meta:
		model = Listing
		fields = ["title", "listing_main_photo", "description", "location"]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from users.models import AppUser

# input_attribute = {"class":"textinput border rounded-lg leading-normal focus:outline-none text-gray-700 px-4 appearance-none bg-white block w-full border-gray-300 py-2"}
# when using the meta tag you can use the input attribute to add css to the form as well.

class RegisterForm(UserCreationForm):
	class Meta:
		model = AppUser
		fields = ["username", "email", "password1", "password2"]

class ProfileForm(ModelForm):
	class Meta:
		model = AppUser
		fields = ["profile_picture", "email", "phone_number", "address"]

SpiffoList/views.py
from django.shortcuts import render
from django.views import View


class WelcomePage(View):
	def get (self, request, *args, **kwargs):
		return render(request, 'users/welcome.html')

	def post (self, request, *args, **kwargs):
		return render(request, 'users/welcome.html')

listings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import ListingCreationForm
from django.http import HttpResponse
from .models import Listing


class ListingCreationView(LoginRequiredMixin, View):
	"""This is where the listing creation is"""

	def get(self, request, *args, **kwargs):
		"""when the page is requested"""
		if request.user.is_authenticated:
			form = ListingCreationForm()
			return render(request, 'listings/listingCreation.html', {'form': form})
		else:
			return redirect('users:login')

	def post(self, request, *args, **kwargs):
		"""when the listing creation form is submitted we need to verify it."""
		if request.user.is_authenticated:
			listing = Listing(owner = request.user)  # init a new listings instance
			form = ListingCreationForm(request.POST, request.FILES, instance = listing)
			if form.is_valid():
				form.save()
				return render(request, 'users/welcome.html', {'form': form})
			else:
				return render(request, 'users/welcome.html', {'form': form})
		else:
			return redirect('users:login')


class ListingUserViewAll(LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			all_listings = Listing.objects.filter(owner = request.user.id)

			return render(request, 'listings/index.html', {'all_listings': all_listings})
		else:
			return redirect('users:login')

	def post(self, request, *args, **kwargs):
		return HttpResponse('<h1>Testing The Listing Page</h1>')


class DestroyListing(LoginRequiredMixin, View):
	def post(self, request, pk: int, *args, **kwargs):
		if request.user.is_authenticated:
			listing = get_object_or_404(Listing, pk = pk, owner = request.user)
			listing.delete()
			return redirect('listings:index')

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from .forms import RegisterForm, ProfileForm


class ProfileView(LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		""""if we get a get request i.e visted the page."""
		form = ProfileForm(instance = request.user)
		return render(request, 'users/profile.html', {'form': form})

	def post(self, request, *args, **kwargs):
		""""if the form is submitted"""
		form = ProfileForm(request.POST, request.FILES, instance = request.user)
		if form.is_valid():
			form.save()
			return redirect('users:profile')
		else:
			return render(request, 'users/profile.html', {'form': form})


class RegisterProfileView(View):
	def get(self, request, *args, **kwargs):
		form = RegisterForm()
		return render(request, 'users/register.html', {'form': form})

	def post(self, request, *args, **kwargs):
		form = RegisterForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('users:profile')
		else:
			return render(request, "users/register.html", {"form": form})

listings/templates/listings/index.html
{% extends "base.html" %}

{% block content %}
    <div class="p-2">
    <div>
    <h1>All Listings</h1>

    {% for listing in all_listings %}
        <div class="card">
            <h2 class="card-title">{{ listing.title }}</h2>
            <div class="card-body">
                <ul>
                    <li>Listings Picture Container: {{ listing.listing_main_photo }}</li>
                    <li><strong>Creator: </strong>{{ listing.owner }}</li>
                    <li><strong>Description: </strong>{{ listing.description }}</li>
                    <li><strong>Location Info: </strong>{{ listing.location }}</li>
                </ul>
            </div>
            <div class="card-actions justify-end">
                <form method="post" action="{% url 'listings:destroy' pk=listing.id %}">
                    {% csrf_token %}
                    <button class="btn btn-warning">Destroy</button>
                </form>
            </div>
        </div>
    {% endfor %}
{% endblock %}

</div>

</div>

listings/templates/listings/listingCreation.html
{%extends "base.html"%}

{% block content %}
<div class="p-2">

</div>

    <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success"> Update </button>
    </form>

{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Tailwind</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
</head>

<body class="bg-gray-50 font-serif leading-normal tracking-normal">
<div class="p-2 container mx-auto">
    <div class="navbar bg-base-100 shadow-xl rounded-box">
        <div class="flex-1">
            <a href="{% url "welcome" %}" class="btn btn-ghost normal-case text-xl">Home</a>
        </div>
         <div class="form-control">
      <input type="text" placeholder="Search" class="input input-bordered" />
    </div>
        <div class="flex-none">
            <ul class="menu menu-horizontal p-0">
                <li><a href="{% url "listings:create" %}">Listing Builder</a></li>
                <li tabindex="0">
                    <a>
                        MyList
                        <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
                    </a>
                    <ul class="p-2 bg-base-100">
                        <li><a>Submenu 1</a></li>
                        <li><a>Submenu 2</a></li>
                    </ul>
                </li>
                 <li tabindex="0">
                    <a>
                        Account
                        <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
                    </a>
                    <ul class="p-2 bg-base-100">
                        <li><a href="{% url "login"  %}">Login</a></li>
                        <li><a href="{% url "logout" %}">Logout</a></li>
                        <li><a href="{% url "users:profile" %}">Edit Profile</a></li>
                        <li><a href="{% url "listings:index" %}">View My Listings</a></li>
                        <li><a href="{% url "users:register" %}">Register</a></li>
                    </ul>
                </li>
                <li>

                </li>
            </ul>
        </div>

    </div>

       <div>
    {% block content %}
    {% endblock %}
    </div>

</div>
</body>
</html>

users/templates/users/profile.html
{%extends "base.html"%}
{% block content %}


    <h1> Profile Page</h1>
    <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success"> Update </button>
    </form>


{% endblock %}

users/templates/users/register.html
{%extends "base.html"%}

{% block content %}

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <div class=""> </div>

    <button type="submit" class="p-2 my-2 btn btn-success"> Register now </button>

</form>

{% endblock %}

users/templates/users/welcome.html
{%extends "base.html"%}

{% block content %}
<div class="p-2">
{#<div>#}
{#    Press <kbd class="kbd kbd-sm">F</kbd> to pay respects.#}
{#</div>#}
</div>
{% endblock %}